### ISSUE TITLE
Broken icon on Windows

### ISSUE THREAD

**Issue by ferPFlores** [ShinjiruApp/Shinjiru#10]
Hi, the icon is broken, i have instead a blank paper sheet
![image](https://user-images.githubusercontent.com/12365536/40942300-649ab4aa-6813-11e8-822f-c80831e288f8.png)
Also, i tried to restore it and i get this message: 
![image](https://user-images.githubusercontent.com/12365536/40942360-8784c1fe-6813-11e8-8f30-4df8b091877a.png)

**Comment by Kazakuri** [comment]
Fixed in d9db881

Update will mostly likely be released this upcoming Saturday.
