### ISSUE TITLE
Unknown module networkauth issues in Ubuntu 18.04

### ISSUE THREAD

**Issue by DJ-TrainR3k** [ShinjiruApp/Shinjiru#17]
As per instruction, I cloned the repo and ran INSTALL.linux and used the default options to install qt using the web installer linked and no matter what modules I add using the manager, I keep getting

`Project ERROR: Unknown module(s) in QT: networkauth`

on every run of the installer.

**Comment by Kazakuri** [comment]
When you expand the selected Qt version on the web installer, there should be a component near the bottom titled "Qt Network Authorization" or something similar, that's the one you want to add.

**Comment by DJ-TrainR3k** [comment]
I was aware of that and I even tried installing that module for every available version and I still get the same error

**Comment by Kazakuri** [comment]
I've been trying to recreate this in a local VM but I can't seem to at all.
What's the output if you run `qmake --version`?

**Comment by DJ-TrainR3k** [comment]
The output is
`QMake version 3.1`
`Using Qt version 5.9.5 in /usr/lib/x86_64-linux-gnu`

I made sure the networkauth (TP) module checkbox for that Qt version was selected and i still get the same output

**Comment by Kazakuri** [comment]
Does either `/usr/lib/x86_64-linux-gnu/libQt5NetworkAuth.so` or `/usr/lib/x86_64-linux-gnu/Qt5NetworkAuth.so` exist?

**Comment by DJ-TrainR3k** [comment]
Neither of those files exist for me

**Comment by Kazakuri** [comment]
Hm, and one of `/usr/lib/x86_64-linux-gnu/libQt5Gui.so` or `/usr/lib/x86_64-linux-gnu/Qt5Gui.so` exists, right?

**Comment by DJ-TrainR3k** [comment]
Yup, libQt5Gui.so exists

**Comment by Kazakuri** [comment]
I'm not sure what's going on, it seems like the version of Qt it's trying to use is different from the one the installer installed.

Can you run `qtchooser -list-versions` to see if there are other versions of Qt laying around somewhere?

**Comment by DJ-TrainR3k** [comment]
Hm, there seems to be multiple versions. It outputs
```
4
5
default
qt4-x86_64-linux-gnu
qt4
qt5-x86_64-linux-gnu
qt5

**Comment by Kazakuri** [comment]
Hm, I imagine that they're all actually pointing to the same thing in the end though.
`qtchooser -print-env -qt=5`
`qtchooser -print-env -qt=qt5-x86_64-linux-gnu`
`qtchooser -print-env -qt=qt5`

all likely output `QTLIBDIR="/usr/lib/x86_64-linux-gnu"`, right?

**Comment by DJ-TrainR3k** [comment]
Yup, all three do pint to /usr/lib/x86_64-linux-gnu

**Comment by Kazakuri** [comment]
Hm, it doesn't seem like the installer actually installed the module.

If you run `find / -name "libQt5NetworkAuth.so"` does it turn up any results at all?

**Comment by DJ-TrainR3k** [comment]
It found two, one in /home/<username>/Qt/5.9.5/gcc_64/lib/ and another in /home/<username>/Qt/5.11.1/gcc_64/lib/

**Comment by DJ-TrainR3k** [comment]
The module issue is gone, but the build fails. The output is here https://pastebin.com/XdMXEkJ3

**Comment by Kazakuri** [comment]
Oh woops, that should have been `libxtst-dev` instead of `libxtst6` installing that one should do the trick.

**Comment by DJ-TrainR3k** [comment]
Ah alright, that worked a treat. Thank you very much for your help, I appreciate it.

**Comment by Kazakuri** [comment]
Sorry that it took so long to work out, Linux can be a bit of a pain sometimes.

Glad it's working!

**Comment by DJ-TrainR3k** [comment]
Ah not quite. Whenever I open the application it keeps requesting for access to anilist and I already did it before. I click authorize and it says callback recieved. The app itself looks alright, but no info from my account shows, and when i try to refresh, it closes with no crash dialogue.

**Comment by Kazakuri** [comment]
Is there anything in `cat ~/.Shinjiru.log` ?

**Comment by DJ-TrainR3k** [comment]
Nope, it doesn't exist

**Comment by Kazakuri** [comment]
Huh, that's weird. It should definitely be using that [path for logging](https://github.com/ShinjiruApp/Shinjiru/blob/92691b26af6a7a34f22e2e50117d547e4289e157/src/paths.cpp#L78)...

I'm pretty sure the issue you're having now is being caused by an openssl issue, can you try installing `openssl-dev` and trying again? You *might* have to re-run the INSTALL.linux script.

**Comment by DJ-TrainR3k** [comment]
I went to the application directory and ran it in terminal and got this out of it. You are right about the openssl issue. https://pastebin.com/VSqbj663

**Comment by Kazakuri** [comment]
Huh, it should be building in release mode, but it's being built in debug mode for some reason if it's logging to the console.

Try doing `sudo apt-get install openssl1.0 libssl1.0-dev` since it seems like Qt is built and linked against OpenSSL 1.0.2

**Comment by DJ-TrainR3k** [comment]
![screenshot from 2018-07-22 18-47-19](https://user-images.githubusercontent.com/13580136/43051450-c9470948-8ddf-11e8-99c5-c7349512bd18.png)
This is what shows up instead of the Allow or Deny prompt from anilist and my credentials do not work.

This is also output in the terminal when run from there
```
[2018-07-22 23:49:05.486] File not found "/home/USER/.local/bin/customMediaPlayers.json"
[2018-07-22 23:49:05.486] QOAuth2AuthorizationCodeFlow::buildAuthenticateUrl: https://anilist.co/api/v2/oauth/authorize?client_id=16&redirect_uri=http://localhost:0/auth&response_type=code&scope&state=6Arm6jI7
/snap/firefox/107/bin/desktop-launch: line 174: /home/USER/snap/firefox/common/.config/user-dirs.dirs: No such file or directory
cp: cannot create regular file '/home/USER/snap/firefox/common/.config/': Not a directory
/snap/firefox/107/bin/desktop-launch: line 177: /home/USER/snap/firefox/common/.config/user-dirs.dirs.md5sum: No such file or directory
/snap/firefox/107/bin/desktop-launch: line 177: /home/USER/snap/firefox/common/.config/user-dirs.locale.md5sum: No such file or directory
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"

**Comment by DJ-TrainR3k** [comment]
Wait, we have success! I reinstalled chromium and was able to authenticate successfully from chromium and now i can access my series in the app. Do not know why it doesn't like firefox though.

**Comment by Kazakuri** [comment]
I think the last time that weird login box thing happened because multiple copies of Shinjiru were open and that was somehow causing issues.

I'm glad to hear that it's finally working though, let me know if you run into any other troubles!
