### ISSUE TITLE
Not Connecting to Anilist (Mint)

### ISSUE THREAD

**Issue by izik1** [ShinjiruApp/Shinjiru#24]
Built from source (548ab131742178d34a05f6c96e7c3b953b299f16). It opens the oauth webpage and accepting the oauth changes it to the `Callback received. Feel free to close this page.` page. However, Shinjiru gives no indication of having actually signed into anything, has blank lists and trying to open the user Home / List pages tries to open the `https://anilist.co/user/0/` and `https://anilist.co/user/0/animelist` pages respectively.
```
$ qmake -v
QMake version 3.1
Using Qt version 5.11.1 in ~/Qt/5.11.1/gcc_64/lib
$ lupdate -version
lupdate version 5.11.1
$ lrelease -version
lrelease version 5.11.1
```
I'm not aware of any logs that I could provide but if they exist I can provide them.

**Comment by Kazakuri** [comment]
It's likely an issue with OpenSSL, the latest version of Qt is linked to OpenSSL 1.0.2 afaik, can you verify that that version is installed?

There should be a [log file in your home directory](https://github.com/ShinjiruApp/Shinjiru/blob/548ab131742178d34a05f6c96e7c3b953b299f16/src/paths.cpp#L78) that should give more information.

**Comment by izik1** [comment]
Few minutes later after some searching I found [this](https://stackoverflow.com/a/42297296/6221420) SO answer, and `apt install libssl1.0-dev` fixed the issue, I would recommend indicating somewhere that OpenSSL versions may cause problems. Thanks for pointing me in the right direction!
-----
I'm not actually sure when to close this? Possibly now?

**Comment by Kazakuri** [comment]
I'll make a commit later today to add a Troubleshooting section to the readme, we can keep this open as a reminder.

**Comment by Kazakuri** [comment]
Added the troubleshooting section in 5b4a4433451703572ea8fa54875936e0c75a1baa
