### ISSUE TITLE
KissAnime detection

### ISSUE THREAD

**Issue by SpaceboyRoss01** [ShinjiruApp/Shinjiru#25]
Will there be support for detecting if the user is watching an anime on KissAnime? I think this will be useful.

**Comment by Kazakuri** [comment]
Hey there! Sorry for not responding to this sooner, it seems like GitHub wasn't sending me e-mails at all.

I'm going to spend a ton of time working on Shinjiru over the Christmas holidays so I'll make sure to add-in support for KissAnime, GogoAnime, and a handful of other streaming websites.

**Comment by SpaceboyRoss01** [comment]
That's great to hear that support for it will be added. That's weird how GitHub didn't send E-mails.

**Comment by Kazakuri** [comment]
Closing this since KissAnime detection was added in cf4f3b480d9e869ef3376ccb9c940212322298bf
