### ISSUE TITLE
[Ubuntu] Trying to uninstall to rebuild shinjiru

### ISSUE THREAD

**Issue by aeryl1999** [ShinjiruApp/Shinjiru#41]
Updated ubuntu and qt and now shinjiru is not working:  Blank UI's again. Just wanted to ask for the uninstall procedure.

**Comment by Kazakuri** [comment]
Sorry for the delay, I was at an anime convention this past weekend.

If you installed by running the `INSTALL.linux` file, the [default prefix](https://github.com/ShinjiruApp/Shinjiru/blob/ae1ba175b5394fbcd8e8c893daabeebe19522587/INSTALL.linux#L30) is `~/.local`

So you should be able to remove the following files:
- `~/.local/bin/Shinjiru`
- `~/.local/share/applications/Shinjiru.desktop`
- `~/.local/share/icons/hicolor/scalable/apps/Shinjiru.svg`
- `~/.local/share/licenses/Shinjiru`
