### ISSUE TITLE
Installation on Manjaro fails

### ISSUE THREAD

**Issue by WhiteSp1rit** [ShinjiruApp/Shinjiru#46]
Got this error when running INSTALL.linux:

```
ui/main_window/views/anime_table.cpp: In member function ‘virtual void Views::AnimeTable::contextMenuEvent(QContextMenuEvent*)’:
ui/main_window/views/anime_table.cpp:184:26: error: invalid use of incomplete type ‘class QContextMenuEvent’
  184 |   contextMenu->exec(event->globalPos());
      |                          ^~
In file included from /usr/include/qt/QtWidgets/qmenu.h:44,
                 from /usr/include/qt/QtWidgets/QMenu:1,
                 from ui/main_window/views/anime_table.h:4,
                 from ui/main_window/views/anime_table.cpp:1:
/usr/include/qt/QtWidgets/qwidget.h:81:7: note: forward declaration of ‘class QContextMenuEvent’
   81 | class QContextMenuEvent;
      |       ^~~~~~~~~~~~~~~~~
make: *** [Makefile:2454: anime_table.o] Error 1
make: *** Waiting for unfinished jobs....
Build error: Compilation failed.
Aborting.
```

all required dependencies mentioned [here](https://github.com/ShinjiruApp/Shinjiru)  were already installed, I did not use qt-specific online installer

also lots of warnings like these:
```
lib/robot/Source/Memory.cc:488:22: warning: missing initializer for member ‘Robot::Memory::Region::Start’ [-Wmissing-field-initializers]
lib/robot/Source/Memory.cc:488:22: warning: missing initializer for member ‘Robot::Memory::Region::Stop’ [-Wmissing-field-initializers]
lib/robot/Source/Memory.cc:488:22: warning: missing initializer for member ‘Robot::Memory::Region::Size’ [-Wmissing-field-initializers]
```

**Comment by Kazakuri** [comment]
Ah, it looks like the header for QContextMenuEvent isn't being included inside QMenu anymore, we should definitely be doing that ourselves though.

If you add `#include <QContextMenuEvent>` to `ui/main_window/views/anime_table.h` does that fix compilation?

**Comment by WhiteSp1rit** [comment]
> If you add `#include <QContextMenuEvent>` to `ui/main_window/views/anime_table.h` does that fix compilation?

No, compilation still fails
I've attached console log file

[output.txt](https://github.com/ShinjiruApp/Shinjiru/files/4021247/output.txt)

**Comment by 3e849f2e5c** [comment]
I managed to compile successfully on Arch Linux after adding
```Cpp
#include <QContextMenuEvent>
```
to `ui/main_window/views/anime_table.h` and 
```Cpp
#include <QVariant>
```
to `ui/settings_dialog/components/torrent_rule.h`

**Comment by WhiteSp1rit** [comment]
> I managed to compile successfully on Arch Linux after adding
> 
> ```c++
> #include <QContextMenuEvent>
> ```
> 
> to `ui/main_window/views/anime_table.h` and
> 
> ```c++
> #include <QVariant>
> ```
> 
> to `ui/settings_dialog/components/torrent_rule.h`

tried adding both of these - still getting same error. 

Just to check, should the includes look like this for example:
```

#ifndef TORRENT_RULE_H
#define TORRENT_RULE_H

#include <QList>
#include <QString>
#include <QVariant>

class TorrentRule {
```

**Comment by 3e849f2e5c** [comment]
That's how I did it, if you cloned the repo and ran INSTALL.linux make sure you edit the files in Shinjiru/Shinjiru because the install script clones the repo too. For example edit `Shinjiru/Shinjiru/ui/settings_dialog/components/torrent_rule.h` instead of `Shinjiru/ui/settings_dialog/components/torrent_rule.h`

**Comment by Kazakuri** [comment]
Yep, it looks like the error was the same after adding that line to the header, so I think @3e849f2e5c might be right that the wrong file is being edited.

Originally I had intended for the `INSTALL.linux` script to work similar to how `rustup` and other programs are installed where you can just pipe the curl output to bash and have it work instead of having to mess with cloning the repo, but it never quite got that far.

**Comment by WhiteSp1rit** [comment]
Edited the correct files - can confirm that compilation succeeded, program works
